export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_CLIENT = 'SET_CURRENT_CLIENT';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'SET_CURRENT_CLIENT';
export const GET_PROFILES = 'GET_PROFILES';
